aaaaaaaaaaaaaaaaaaaaaaagh
Trying to make it bundle nw.js inside the single file executable
instead of having the executable download nw.js and cache it

Current state:

 2026-05-22 01:42:18 ⌚  Cardboard in ~/Projects/nw-screensaver
± |downgrade-nexe {2} U:2 ✗| → npm run OLD:build && ./nw-screensaver.scr.exe

> nw-screensaver@1.5.5 OLD:build
> coffee --compile --transpile wrapper.coffee & coffee make-wrapper.coffee

Get NW.js v0.54.1 (sdk) from the cache or download it to temp/nwjs_cache
dir contents [
  'manifest.json',
  'nwjs-sdk-v0.54.1-win-x64',
  'nwjs-sdk-v0.54.1-win-x64.zip',
  'shasum'
]
nw_exe temp\nwjs_cache\nwjs-sdk-v0.54.1-win-x64\nw.exe
nw_exe exists? true
Zip app to app.zip
Compile ./wrapper.js to nw-screensaver.scr with nexe
----> framework => nodejs
----> embedResources [ 'app.zip', 'temp\\nwjs_cache\\nwjs-sdk-v0.54.1-win-x64.zip' ]
----> resource -> C:\Users\Isaiah\Projects\nw-screensaver\temp\nodejs\0.12.6\node-v0.12.6\lib\nexeres.js
----> bundle ./wrapper.js
----> executing browserify via API
----> already patched node.cc
----> vcbuild [make stage]
node:internal/child_process:420
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:787:9)
    at Object.make (C:\Users\Isaiah\Projects\nw-screensaver\node_modules\nexe\lib\exe.js:483:25)
    at makeExecutable (C:\Users\Isaiah\Projects\nw-screensaver\node_modules\nexe\lib\exe.js:223:20)
    at fn (C:\Users\Isaiah\Projects\nw-screensaver\node_modules\async\lib\async.js:746:34)
    at C:\Users\Isaiah\Projects\nw-screensaver\node_modules\async\lib\async.js:1213:16
    at C:\Users\Isaiah\Projects\nw-screensaver\node_modules\async\lib\async.js:166:37
    at C:\Users\Isaiah\Projects\nw-screensaver\node_modules\async\lib\async.js:706:43
    at C:\Users\Isaiah\Projects\nw-screensaver\node_modules\async\lib\async.js:167:37
    at C:\Users\Isaiah\Projects\nw-screensaver\node_modules\async\lib\async.js:1209:30
    at C:\Users\Isaiah\Projects\nw-screensaver\node_modules\nexe\lib\exe.js:203:13
    at FSReqCallback.oncomplete (node:fs:186:23) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v22.22.0